//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taksówki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kierowca
    {
        public Kierowca()
        {
            this.Status_kierowcy = new HashSet<Status_kierowcy>();
            this.KierowcaZlecenie = new HashSet<KierowcaZlecenie>();
        }
    
        public int ID_kierowcy { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Nr_telefonu { get; set; }
    
        public virtual ICollection<Status_kierowcy> Status_kierowcy { get; set; }
        public virtual ICollection<KierowcaZlecenie> KierowcaZlecenie { get; set; }
    }
}
