//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taksówki
{
    using System;
    using System.Collections.Generic;
    
    public partial class listwa_magazyn
    {
        public int idListwa { get; set; }
        public Nullable<int> idMagazyn { get; set; }
        public decimal ileMetrow { get; set; }
    
        public virtual listwy listwy { get; set; }
        public virtual magazyn magazyn { get; set; }
    }
}
