//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taksówki
{
    using System;
    using System.Collections.Generic;
    
    public partial class listwy
    {
        public listwy()
        {
            this.listwa_magazyn = new HashSet<listwa_magazyn>();
            this.zdarzenia = new HashSet<zdarzenia>();
        }
    
        public int idListwy { get; set; }
        public string numerListwy { get; set; }
        public string kolor { get; set; }
        public Nullable<int> grubosc { get; set; }
        public Nullable<decimal> cena { get; set; }
        public string uwagi { get; set; }
        public string kodKreskowy { get; set; }
    
        public virtual ICollection<listwa_magazyn> listwa_magazyn { get; set; }
        public virtual ICollection<zdarzenia> zdarzenia { get; set; }
    }
}
