//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taksówki
{
    using System;
    using System.Collections.Generic;
    
    public partial class magazyn
    {
        public magazyn()
        {
            this.listwa_magazyn = new HashSet<listwa_magazyn>();
            this.zdarzenia = new HashSet<zdarzenia>();
        }
    
        public int idMagazyn { get; set; }
        public string nazwa { get; set; }
        public string miejscowosc { get; set; }
        public string ulica { get; set; }
        public string numerLokalu { get; set; }
    
        public virtual ICollection<listwa_magazyn> listwa_magazyn { get; set; }
        public virtual ICollection<zdarzenia> zdarzenia { get; set; }
    }
}
