//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taksówki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samochod
    {
        public Samochod()
        {
            this.Status_kierowcy = new HashSet<Status_kierowcy>();
        }
    
        public int ID_samochodu { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public int Przebieg { get; set; }
        public bool Sprawnosc { get; set; }
        public bool VIP { get; set; }
    
        public virtual ICollection<Status_kierowcy> Status_kierowcy { get; set; }
    }
}
