//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taksówki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_kierowcy
    {
        public int ID_statusu { get; set; }
        public int Kierowca { get; set; }
        public Nullable<int> Samochod { get; set; }
        public bool W_pracy { get; set; }
        public Nullable<decimal> Pozycja_szer { get; set; }
        public Nullable<decimal> Pozycja_dl { get; set; }
        public Nullable<System.DateTime> Czas_zmiany { get; set; }
    
        public virtual Kierowca Kierowca1 { get; set; }
        public virtual Samochod Samochod1 { get; set; }
    }
}
