//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taksówki
{
    using System;
    using System.Collections.Generic;
    
    public partial class zdarzenia
    {
        public int idzdarzenia { get; set; }
        public string nazwaZdarzenia { get; set; }
        public int listwa { get; set; }
        public Nullable<decimal> ilosc { get; set; }
        public Nullable<int> magazyn { get; set; }
        public Nullable<int> uzytkownik { get; set; }
        public System.DateTime data { get; set; }
        public System.TimeSpan godzina { get; set; }
    
        public virtual listwy listwy { get; set; }
        public virtual magazyn magazyn1 { get; set; }
        public virtual uzytkownicy uzytkownicy { get; set; }
    }
}
