//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taksówki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zlecenie
    {
        public Zlecenie()
        {
            this.KierowcaZlecenie = new HashSet<KierowcaZlecenie>();
        }
    
        public int ID_zlecenie { get; set; }
        public decimal Skad_szer { get; set; }
        public decimal Skad_dl { get; set; }
        public decimal Dokad_szer { get; set; }
        public decimal Dokad_dl { get; set; }
        public System.DateTime Czas_poczatkowy { get; set; }
        public int Mozliwe_spoznienie { get; set; }
        public int Przyblizony_czas_drogi { get; set; }
        public bool VIP { get; set; }
    
        public virtual ICollection<KierowcaZlecenie> KierowcaZlecenie { get; set; }
    }
}
